// Code generated by herdr-api-gen. DO NOT EDIT.

package herdr

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
)

// EventKind is the "event" field of a lifecycle event envelope.
type EventKind string

// EventKind values.
const (
	EventKindWorkspaceCreated         EventKind = "workspace_created"
	EventKindWorkspaceUpdated         EventKind = "workspace_updated"
	EventKindWorkspaceMetadataUpdated EventKind = "workspace_metadata_updated"
	EventKindWorkspaceClosed          EventKind = "workspace_closed"
	EventKindWorkspaceRenamed         EventKind = "workspace_renamed"
	EventKindWorkspaceMoved           EventKind = "workspace_moved"
	EventKindWorkspaceReordered       EventKind = "workspace_reordered"
	EventKindWorkspaceFocused         EventKind = "workspace_focused"
	EventKindWorktreeCreated          EventKind = "worktree_created"
	EventKindWorktreeOpened           EventKind = "worktree_opened"
	EventKindWorktreeRemoved          EventKind = "worktree_removed"
	EventKindTabCreated               EventKind = "tab_created"
	EventKindTabClosed                EventKind = "tab_closed"
	EventKindTabRenamed               EventKind = "tab_renamed"
	EventKindTabMoved                 EventKind = "tab_moved"
	EventKindTabFocused               EventKind = "tab_focused"
	EventKindPaneCreated              EventKind = "pane_created"
	EventKindPaneClosed               EventKind = "pane_closed"
	EventKindPaneUpdated              EventKind = "pane_updated"
	EventKindPaneFocused              EventKind = "pane_focused"
	EventKindPaneMoved                EventKind = "pane_moved"
	EventKindPaneOutputChanged        EventKind = "pane_output_changed"
	EventKindPaneExited               EventKind = "pane_exited"
	EventKindPaneAgentDetected        EventKind = "pane_agent_detected"
	EventKindPaneAgentStatusChanged   EventKind = "pane_agent_status_changed"
	EventKindLayoutUpdated            EventKind = "layout_updated"
)

// DotName returns the dotted spelling of the event name, matching
// EventKind::dot_name in herdr: the first underscore becomes a dot.
func (k EventKind) DotName() string {
	return strings.Replace(string(k), "_", ".", 1)
}

// Event is a decoded event payload.
type Event interface {
	// EventName returns the dotted name of the event, for example
	// "pane.created".
	EventName() string
}

// EventEnvelope is one event line pushed on a subscription connection.
type EventEnvelope struct {
	Event EventKind `json:"event"`
	Data  Event     `json:"data"`
}

// UnmarshalJSON decodes the payload according to the event name.
func (e *EventEnvelope) UnmarshalJSON(data []byte) error {
	var aux struct {
		Event EventKind       `json:"event"`
		Data  json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	e.Event = aux.Event
	e.Data = nil
	if len(aux.Data) == 0 || string(aux.Data) == "null" {
		return nil
	}
	decoded, err := DecodeEvent(string(aux.Event), aux.Data)
	if err != nil {
		return err
	}
	e.Data = decoded
	return nil
}

// DecodeEvent decodes an event payload. A dotted event name selects one of
// the dedicated subscription payloads; any other name selects the variant
// named by the payload's "type" field. An unknown name is reported as
// *UnknownEventError.
func DecodeEvent(event string, data json.RawMessage) (Event, error) {
	if strings.Contains(event, ".") {
		switch event {
		case "pane.output_matched":
			var value PaneOutputMatchedEvent
			if err := json.Unmarshal(data, &value); err != nil {
				return nil, err
			}
			return &value, nil
		case "pane.agent_status_changed":
			var value PaneAgentStatusChangedEvent
			if err := json.Unmarshal(data, &value); err != nil {
				return nil, err
			}
			return &value, nil
		case "pane.scroll_changed":
			var value PaneScrollChangedEvent
			if err := json.Unmarshal(data, &value); err != nil {
				return nil, err
			}
			return &value, nil
		}
		return nil, &UnknownEventError{Event: event, Data: append(json.RawMessage(nil), data...)}
	}
	var head struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &head); err != nil {
		return nil, err
	}
	switch head.Type {
	case "layout_updated":
		var value LayoutUpdatedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane_agent_detected":
		var value PaneAgentDetectedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane_agent_status_changed":
		var value PaneAgentStatusChangedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane_closed":
		var value PaneClosedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane_created":
		var value PaneCreatedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane_exited":
		var value PaneExitedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane_focused":
		var value PaneFocusedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane_moved":
		var value PaneMovedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane_output_changed":
		var value PaneOutputChangedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane_updated":
		var value PaneUpdatedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "tab_closed":
		var value TabClosedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "tab_created":
		var value TabCreatedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "tab_focused":
		var value TabFocusedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "tab_moved":
		var value TabMovedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "tab_renamed":
		var value TabRenamedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "workspace_closed":
		var value WorkspaceClosedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "workspace_created":
		var value WorkspaceCreatedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "workspace_focused":
		var value WorkspaceFocusedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "workspace_metadata_updated":
		var value WorkspaceMetadataUpdatedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "workspace_moved":
		var value WorkspaceMovedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "workspace_renamed":
		var value WorkspaceRenamedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "workspace_reordered":
		var value WorkspaceReorderedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "workspace_updated":
		var value WorkspaceUpdatedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "worktree_created":
		var value WorktreeCreatedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "worktree_opened":
		var value WorktreeOpenedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "worktree_removed":
		var value WorktreeRemovedEvent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	}
	return nil, &UnknownEventError{Event: event, Data: append(json.RawMessage(nil), data...)}
}

// UnknownEventError is returned for an event that is not in the schema the
// code was generated from. Data holds the undecoded payload.
type UnknownEventError struct {
	Event string
	Data  json.RawMessage
}

func (e *UnknownEventError) Error() string {
	return fmt.Sprintf("herdr: unknown event %q", e.Event)
}

// NextEvent reads the next line the server pushes and decodes its payload.
// The errors of Next are returned unchanged; payload decoding failures
// carry OpDecode.
func (s *Stream) NextEvent(ctx context.Context) (Event, error) {
	raw, err := s.Next(ctx)
	if err != nil {
		return nil, err
	}
	event, err := DecodeEvent(raw.Event, raw.Data)
	return event, opError(s.method, OpDecode, err)
}

// LayoutUpdatedEvent is the "layout.updated" event payload.
type LayoutUpdatedEvent struct {
	Layout PaneLayoutSnapshot `json:"layout"`
}

// EventName returns "layout.updated".
func (LayoutUpdatedEvent) EventName() string { return "layout.updated" }

// MarshalJSON writes the object with its "type" field.
func (v LayoutUpdatedEvent) MarshalJSON() ([]byte, error) {
	type alias LayoutUpdatedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "layout_updated", alias: alias(v)})
}

// PaneAgentDetectedEvent is the "pane.agent_detected" event payload.
type PaneAgentDetectedEvent struct {
	Agent       *string      `json:"agent,omitempty"`
	FinalStatus *AgentStatus `json:"final_status,omitempty"`
	PaneID      string       `json:"pane_id"`
	Released    *bool        `json:"released,omitempty"`
	WorkspaceID string       `json:"workspace_id"`
}

// EventName returns "pane.agent_detected".
func (PaneAgentDetectedEvent) EventName() string { return "pane.agent_detected" }

// MarshalJSON writes the object with its "type" field.
func (v PaneAgentDetectedEvent) MarshalJSON() ([]byte, error) {
	type alias PaneAgentDetectedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "pane_agent_detected", alias: alias(v)})
}

// PaneAgentStatusChangedEvent is the "pane.agent_status_changed" event
// payload.
type PaneAgentStatusChangedEvent struct {
	Agent        *string           `json:"agent,omitempty"`
	AgentStatus  AgentStatus       `json:"agent_status"`
	DisplayAgent *string           `json:"display_agent,omitempty"`
	PaneID       string            `json:"pane_id"`
	StateLabels  map[string]string `json:"state_labels,omitempty"`
	Title        *string           `json:"title,omitempty"`
	WorkspaceID  string            `json:"workspace_id"`
}

// EventName returns "pane.agent_status_changed".
func (PaneAgentStatusChangedEvent) EventName() string { return "pane.agent_status_changed" }

// MarshalJSON writes the object with its "type" field.
func (v PaneAgentStatusChangedEvent) MarshalJSON() ([]byte, error) {
	type alias PaneAgentStatusChangedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "pane_agent_status_changed", alias: alias(v)})
}

// PaneClosedEvent is the "pane.closed" event payload.
type PaneClosedEvent struct {
	PaneID      string `json:"pane_id"`
	WorkspaceID string `json:"workspace_id"`
}

// EventName returns "pane.closed".
func (PaneClosedEvent) EventName() string { return "pane.closed" }

// MarshalJSON writes the object with its "type" field.
func (v PaneClosedEvent) MarshalJSON() ([]byte, error) {
	type alias PaneClosedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "pane_closed", alias: alias(v)})
}

// PaneCreatedEvent is the "pane.created" event payload.
type PaneCreatedEvent struct {
	Pane PaneInfo `json:"pane"`
}

// EventName returns "pane.created".
func (PaneCreatedEvent) EventName() string { return "pane.created" }

// MarshalJSON writes the object with its "type" field.
func (v PaneCreatedEvent) MarshalJSON() ([]byte, error) {
	type alias PaneCreatedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "pane_created", alias: alias(v)})
}

// PaneExitedEvent is the "pane.exited" event payload.
type PaneExitedEvent struct {
	PaneID      string `json:"pane_id"`
	WorkspaceID string `json:"workspace_id"`
}

// EventName returns "pane.exited".
func (PaneExitedEvent) EventName() string { return "pane.exited" }

// MarshalJSON writes the object with its "type" field.
func (v PaneExitedEvent) MarshalJSON() ([]byte, error) {
	type alias PaneExitedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "pane_exited", alias: alias(v)})
}

// PaneFocusedEvent is the "pane.focused" event payload.
type PaneFocusedEvent struct {
	PaneID      string `json:"pane_id"`
	WorkspaceID string `json:"workspace_id"`
}

// EventName returns "pane.focused".
func (PaneFocusedEvent) EventName() string { return "pane.focused" }

// MarshalJSON writes the object with its "type" field.
func (v PaneFocusedEvent) MarshalJSON() ([]byte, error) {
	type alias PaneFocusedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "pane_focused", alias: alias(v)})
}

// PaneMovedEvent is the "pane.moved" event payload.
type PaneMovedEvent struct {
	ClosedTabID         *string        `json:"closed_tab_id,omitempty"`
	ClosedWorkspaceID   *string        `json:"closed_workspace_id,omitempty"`
	CreatedTab          *TabInfo       `json:"created_tab,omitempty"`
	CreatedWorkspace    *WorkspaceInfo `json:"created_workspace,omitempty"`
	Pane                PaneInfo       `json:"pane"`
	PreviousPaneID      string         `json:"previous_pane_id"`
	PreviousTabID       string         `json:"previous_tab_id"`
	PreviousWorkspaceID string         `json:"previous_workspace_id"`
}

// EventName returns "pane.moved".
func (PaneMovedEvent) EventName() string { return "pane.moved" }

// MarshalJSON writes the object with its "type" field.
func (v PaneMovedEvent) MarshalJSON() ([]byte, error) {
	type alias PaneMovedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "pane_moved", alias: alias(v)})
}

// PaneOutputChangedEvent is the "pane.output_changed" event payload.
type PaneOutputChangedEvent struct {
	PaneID      string `json:"pane_id"`
	Revision    uint64 `json:"revision"`
	WorkspaceID string `json:"workspace_id"`
}

// EventName returns "pane.output_changed".
func (PaneOutputChangedEvent) EventName() string { return "pane.output_changed" }

// MarshalJSON writes the object with its "type" field.
func (v PaneOutputChangedEvent) MarshalJSON() ([]byte, error) {
	type alias PaneOutputChangedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "pane_output_changed", alias: alias(v)})
}

// PaneOutputMatchedEvent is the "pane.output_matched" event payload.
type PaneOutputMatchedEvent struct {
	MatchedLine string         `json:"matched_line"`
	PaneID      string         `json:"pane_id"`
	Read        PaneReadResult `json:"read"`
}

// EventName returns "pane.output_matched".
func (PaneOutputMatchedEvent) EventName() string { return "pane.output_matched" }

// PaneScrollChangedEvent is the "pane.scroll_changed" event payload.
type PaneScrollChangedEvent struct {
	PaneID      string         `json:"pane_id"`
	Scroll      PaneScrollInfo `json:"scroll"`
	WorkspaceID string         `json:"workspace_id"`
}

// EventName returns "pane.scroll_changed".
func (PaneScrollChangedEvent) EventName() string { return "pane.scroll_changed" }

// PaneUpdatedEvent is the "pane.updated" event payload.
type PaneUpdatedEvent struct {
	Pane PaneInfo `json:"pane"`
}

// EventName returns "pane.updated".
func (PaneUpdatedEvent) EventName() string { return "pane.updated" }

// MarshalJSON writes the object with its "type" field.
func (v PaneUpdatedEvent) MarshalJSON() ([]byte, error) {
	type alias PaneUpdatedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "pane_updated", alias: alias(v)})
}

// TabClosedEvent is the "tab.closed" event payload.
type TabClosedEvent struct {
	TabID       string `json:"tab_id"`
	WorkspaceID string `json:"workspace_id"`
}

// EventName returns "tab.closed".
func (TabClosedEvent) EventName() string { return "tab.closed" }

// MarshalJSON writes the object with its "type" field.
func (v TabClosedEvent) MarshalJSON() ([]byte, error) {
	type alias TabClosedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "tab_closed", alias: alias(v)})
}

// TabCreatedEvent is the "tab.created" event payload.
type TabCreatedEvent struct {
	Tab TabInfo `json:"tab"`
}

// EventName returns "tab.created".
func (TabCreatedEvent) EventName() string { return "tab.created" }

// MarshalJSON writes the object with its "type" field.
func (v TabCreatedEvent) MarshalJSON() ([]byte, error) {
	type alias TabCreatedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "tab_created", alias: alias(v)})
}

// TabFocusedEvent is the "tab.focused" event payload.
type TabFocusedEvent struct {
	TabID       string `json:"tab_id"`
	WorkspaceID string `json:"workspace_id"`
}

// EventName returns "tab.focused".
func (TabFocusedEvent) EventName() string { return "tab.focused" }

// MarshalJSON writes the object with its "type" field.
func (v TabFocusedEvent) MarshalJSON() ([]byte, error) {
	type alias TabFocusedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "tab_focused", alias: alias(v)})
}

// TabMovedEvent is the "tab.moved" event payload.
type TabMovedEvent struct {
	InsertIndex uint64    `json:"insert_index"`
	TabID       string    `json:"tab_id"`
	Tabs        []TabInfo `json:"tabs"`
	WorkspaceID string    `json:"workspace_id"`
}

// EventName returns "tab.moved".
func (TabMovedEvent) EventName() string { return "tab.moved" }

// MarshalJSON writes the object with its "type" field.
func (v TabMovedEvent) MarshalJSON() ([]byte, error) {
	type alias TabMovedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "tab_moved", alias: alias(v)})
}

// TabRenamedEvent is the "tab.renamed" event payload.
type TabRenamedEvent struct {
	Label       string `json:"label"`
	TabID       string `json:"tab_id"`
	WorkspaceID string `json:"workspace_id"`
}

// EventName returns "tab.renamed".
func (TabRenamedEvent) EventName() string { return "tab.renamed" }

// MarshalJSON writes the object with its "type" field.
func (v TabRenamedEvent) MarshalJSON() ([]byte, error) {
	type alias TabRenamedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "tab_renamed", alias: alias(v)})
}

// WorkspaceClosedEvent is the "workspace.closed" event payload.
type WorkspaceClosedEvent struct {
	Workspace   *WorkspaceInfo `json:"workspace,omitempty"`
	WorkspaceID string         `json:"workspace_id"`
}

// EventName returns "workspace.closed".
func (WorkspaceClosedEvent) EventName() string { return "workspace.closed" }

// MarshalJSON writes the object with its "type" field.
func (v WorkspaceClosedEvent) MarshalJSON() ([]byte, error) {
	type alias WorkspaceClosedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "workspace_closed", alias: alias(v)})
}

// WorkspaceCreatedEvent is the "workspace.created" event payload.
type WorkspaceCreatedEvent struct {
	Workspace WorkspaceInfo `json:"workspace"`
}

// EventName returns "workspace.created".
func (WorkspaceCreatedEvent) EventName() string { return "workspace.created" }

// MarshalJSON writes the object with its "type" field.
func (v WorkspaceCreatedEvent) MarshalJSON() ([]byte, error) {
	type alias WorkspaceCreatedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "workspace_created", alias: alias(v)})
}

// WorkspaceFocusedEvent is the "workspace.focused" event payload.
type WorkspaceFocusedEvent struct {
	WorkspaceID string `json:"workspace_id"`
}

// EventName returns "workspace.focused".
func (WorkspaceFocusedEvent) EventName() string { return "workspace.focused" }

// MarshalJSON writes the object with its "type" field.
func (v WorkspaceFocusedEvent) MarshalJSON() ([]byte, error) {
	type alias WorkspaceFocusedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "workspace_focused", alias: alias(v)})
}

// WorkspaceMetadataUpdatedEvent is the "workspace.metadata_updated" event
// payload.
type WorkspaceMetadataUpdatedEvent struct {
	Workspace WorkspaceInfo `json:"workspace"`
}

// EventName returns "workspace.metadata_updated".
func (WorkspaceMetadataUpdatedEvent) EventName() string { return "workspace.metadata_updated" }

// MarshalJSON writes the object with its "type" field.
func (v WorkspaceMetadataUpdatedEvent) MarshalJSON() ([]byte, error) {
	type alias WorkspaceMetadataUpdatedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "workspace_metadata_updated", alias: alias(v)})
}

// WorkspaceMovedEvent is the "workspace.moved" event payload.
type WorkspaceMovedEvent struct {
	InsertIndex uint64          `json:"insert_index"`
	WorkspaceID string          `json:"workspace_id"`
	Workspaces  []WorkspaceInfo `json:"workspaces"`
}

// EventName returns "workspace.moved".
func (WorkspaceMovedEvent) EventName() string { return "workspace.moved" }

// MarshalJSON writes the object with its "type" field.
func (v WorkspaceMovedEvent) MarshalJSON() ([]byte, error) {
	type alias WorkspaceMovedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "workspace_moved", alias: alias(v)})
}

// WorkspaceRenamedEvent is the "workspace.renamed" event payload.
type WorkspaceRenamedEvent struct {
	Label       string `json:"label"`
	WorkspaceID string `json:"workspace_id"`
}

// EventName returns "workspace.renamed".
func (WorkspaceRenamedEvent) EventName() string { return "workspace.renamed" }

// MarshalJSON writes the object with its "type" field.
func (v WorkspaceRenamedEvent) MarshalJSON() ([]byte, error) {
	type alias WorkspaceRenamedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "workspace_renamed", alias: alias(v)})
}

// WorkspaceReorderedEvent is the "workspace.reordered" event payload.
type WorkspaceReorderedEvent struct {
	BeforeWorkspaceID *string         `json:"before_workspace_id,omitempty"`
	WorkspaceIds      []string        `json:"workspace_ids"`
	Workspaces        []WorkspaceInfo `json:"workspaces"`
}

// EventName returns "workspace.reordered".
func (WorkspaceReorderedEvent) EventName() string { return "workspace.reordered" }

// MarshalJSON writes the object with its "type" field.
func (v WorkspaceReorderedEvent) MarshalJSON() ([]byte, error) {
	type alias WorkspaceReorderedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "workspace_reordered", alias: alias(v)})
}

// WorkspaceUpdatedEvent is the "workspace.updated" event payload.
type WorkspaceUpdatedEvent struct {
	Workspace WorkspaceInfo `json:"workspace"`
}

// EventName returns "workspace.updated".
func (WorkspaceUpdatedEvent) EventName() string { return "workspace.updated" }

// MarshalJSON writes the object with its "type" field.
func (v WorkspaceUpdatedEvent) MarshalJSON() ([]byte, error) {
	type alias WorkspaceUpdatedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "workspace_updated", alias: alias(v)})
}

// WorktreeCreatedEvent is the "worktree.created" event payload.
type WorktreeCreatedEvent struct {
	Workspace WorkspaceInfo `json:"workspace"`
	Worktree  WorktreeInfo  `json:"worktree"`
}

// EventName returns "worktree.created".
func (WorktreeCreatedEvent) EventName() string { return "worktree.created" }

// MarshalJSON writes the object with its "type" field.
func (v WorktreeCreatedEvent) MarshalJSON() ([]byte, error) {
	type alias WorktreeCreatedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "worktree_created", alias: alias(v)})
}

// WorktreeOpenedEvent is the "worktree.opened" event payload.
type WorktreeOpenedEvent struct {
	AlreadyOpen bool          `json:"already_open"`
	Workspace   WorkspaceInfo `json:"workspace"`
	Worktree    WorktreeInfo  `json:"worktree"`
}

// EventName returns "worktree.opened".
func (WorktreeOpenedEvent) EventName() string { return "worktree.opened" }

// MarshalJSON writes the object with its "type" field.
func (v WorktreeOpenedEvent) MarshalJSON() ([]byte, error) {
	type alias WorktreeOpenedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "worktree_opened", alias: alias(v)})
}

// WorktreeRemovedEvent is the "worktree.removed" event payload.
type WorktreeRemovedEvent struct {
	Forced      bool           `json:"forced"`
	Workspace   *WorkspaceInfo `json:"workspace,omitempty"`
	WorkspaceID string         `json:"workspace_id"`
	Worktree    WorktreeInfo   `json:"worktree"`
}

// EventName returns "worktree.removed".
func (WorktreeRemovedEvent) EventName() string { return "worktree.removed" }

// MarshalJSON writes the object with its "type" field.
func (v WorktreeRemovedEvent) MarshalJSON() ([]byte, error) {
	type alias WorktreeRemovedEvent
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "worktree_removed", alias: alias(v)})
}
