// Code generated by herdr-api-gen. DO NOT EDIT.

package herdr

import "context"

// Method names of the Herdr API.
const (
	MethodAgentExplain               = "agent.explain"
	MethodAgentFocus                 = "agent.focus"
	MethodAgentGet                   = "agent.get"
	MethodAgentList                  = "agent.list"
	MethodAgentPrompt                = "agent.prompt"
	MethodAgentRead                  = "agent.read"
	MethodAgentRename                = "agent.rename"
	MethodAgentSendKeys              = "agent.send_keys"
	MethodAgentStart                 = "agent.start"
	MethodAgentViewClear             = "agent.view.clear"
	MethodAgentViewSet               = "agent.view.set"
	MethodAgentWait                  = "agent.wait"
	MethodClientShellSurfaceSet      = "client_shell.surface.set"
	MethodClientWindowTitleClear     = "client.window_title.clear"
	MethodClientWindowTitleSet       = "client.window_title.set"
	MethodCommandInvoke              = "command.invoke"
	MethodEventsSubscribe            = "events.subscribe"
	MethodEventsWait                 = "events.wait"
	MethodIntegrationInstall         = "integration.install"
	MethodIntegrationList            = "integration.list"
	MethodIntegrationUninstall       = "integration.uninstall"
	MethodLayoutApply                = "layout.apply"
	MethodLayoutExport               = "layout.export"
	MethodLayoutSetSplitRatio        = "layout.set_split_ratio"
	MethodNotificationShow           = "notification.show"
	MethodPaneClearAgentAuthority    = "pane.clear_agent_authority"
	MethodPaneClose                  = "pane.close"
	MethodPaneCopyMotion             = "pane.copy_motion"
	MethodPaneCopySearch             = "pane.copy_search"
	MethodPaneCurrent                = "pane.current"
	MethodPaneEdges                  = "pane.edges"
	MethodPaneEditScrollback         = "pane.edit_scrollback"
	MethodPaneFocus                  = "pane.focus"
	MethodPaneFocusDirection         = "pane.focus_direction"
	MethodPaneGet                    = "pane.get"
	MethodPaneGraphicsClear          = "pane.graphics.clear"
	MethodPaneGraphicsInfo           = "pane.graphics.info"
	MethodPaneGraphicsSet            = "pane.graphics.set"
	MethodPaneInputSet               = "pane.input.set"
	MethodPaneLayout                 = "pane.layout"
	MethodPaneLinkActivate           = "pane.link.activate"
	MethodPaneLinkResolve            = "pane.link.resolve"
	MethodPaneList                   = "pane.list"
	MethodPaneMove                   = "pane.move"
	MethodPaneNeighbor               = "pane.neighbor"
	MethodPaneProcessInfo            = "pane.process_info"
	MethodPaneRead                   = "pane.read"
	MethodPaneReleaseAgent           = "pane.release_agent"
	MethodPaneRename                 = "pane.rename"
	MethodPaneReportAgent            = "pane.report_agent"
	MethodPaneReportAgentSession     = "pane.report_agent_session"
	MethodPaneReportMetadata         = "pane.report_metadata"
	MethodPaneResize                 = "pane.resize"
	MethodPaneScroll                 = "pane.scroll"
	MethodPaneSelectionRead          = "pane.selection.read"
	MethodPaneSendInput              = "pane.send_input"
	MethodPaneSendKeys               = "pane.send_keys"
	MethodPaneSendText               = "pane.send_text"
	MethodPaneSplit                  = "pane.split"
	MethodPaneSwap                   = "pane.swap"
	MethodPaneWaitForOutput          = "pane.wait_for_output"
	MethodPaneZoom                   = "pane.zoom"
	MethodPing                       = "ping"
	MethodPluginActionInvoke         = "plugin.action.invoke"
	MethodPluginActionList           = "plugin.action.list"
	MethodPluginDisable              = "plugin.disable"
	MethodPluginEnable               = "plugin.enable"
	MethodPluginLink                 = "plugin.link"
	MethodPluginList                 = "plugin.list"
	MethodPluginLogList              = "plugin.log.list"
	MethodPluginPaneClose            = "plugin.pane.close"
	MethodPluginPaneFocus            = "plugin.pane.focus"
	MethodPluginPaneOpen             = "plugin.pane.open"
	MethodPluginUnlink               = "plugin.unlink"
	MethodPopupClose                 = "popup.close"
	MethodProductAnnouncementDismiss = "product_announcement.dismiss"
	MethodReleaseNotesDismiss        = "release_notes.dismiss"
	MethodServerAgentManifests       = "server.agent_manifests"
	MethodServerLiveHandoff          = "server.live_handoff"
	MethodServerReloadAgentManifests = "server.reload_agent_manifests"
	MethodServerReloadConfig         = "server.reload_config"
	MethodServerStop                 = "server.stop"
	MethodSessionSnapshot            = "session.snapshot"
	MethodTabClose                   = "tab.close"
	MethodTabCreate                  = "tab.create"
	MethodTabFocus                   = "tab.focus"
	MethodTabGet                     = "tab.get"
	MethodTabList                    = "tab.list"
	MethodTabMove                    = "tab.move"
	MethodTabRename                  = "tab.rename"
	MethodWorkspaceClose             = "workspace.close"
	MethodWorkspaceCreate            = "workspace.create"
	MethodWorkspaceFocus             = "workspace.focus"
	MethodWorkspaceGet               = "workspace.get"
	MethodWorkspaceList              = "workspace.list"
	MethodWorkspaceMove              = "workspace.move"
	MethodWorkspaceMoveBlock         = "workspace.move_block"
	MethodWorkspaceRename            = "workspace.rename"
	MethodWorkspaceReportMetadata    = "workspace.report_metadata"
	MethodWorktreeCreate             = "worktree.create"
	MethodWorktreeList               = "worktree.list"
	MethodWorktreeOpen               = "worktree.open"
	MethodWorktreeRemove             = "worktree.remove"
)

// AgentExplain calls "agent.explain".
func (c *Client) AgentExplain(ctx context.Context, params AgentTarget) (*AgentExplainResponse, error) {
	raw, err := c.CallRaw(ctx, MethodAgentExplain, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodAgentExplain, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentExplainResponse)
	if !ok {
		return nil, opError(MethodAgentExplain, OpDecode, &UnexpectedResultError{Method: MethodAgentExplain, Want: "agent_explain", Got: result.ResultType()})
	}
	return typed, nil
}

// AgentFocus calls "agent.focus".
func (c *Client) AgentFocus(ctx context.Context, params AgentTarget) (*AgentInfoResponse, error) {
	raw, err := c.CallRaw(ctx, MethodAgentFocus, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodAgentFocus, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentInfoResponse)
	if !ok {
		return nil, opError(MethodAgentFocus, OpDecode, &UnexpectedResultError{Method: MethodAgentFocus, Want: "agent_info", Got: result.ResultType()})
	}
	return typed, nil
}

// AgentGet calls "agent.get".
func (c *Client) AgentGet(ctx context.Context, params AgentTarget) (*AgentInfoResponse, error) {
	raw, err := c.CallRaw(ctx, MethodAgentGet, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodAgentGet, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentInfoResponse)
	if !ok {
		return nil, opError(MethodAgentGet, OpDecode, &UnexpectedResultError{Method: MethodAgentGet, Want: "agent_info", Got: result.ResultType()})
	}
	return typed, nil
}

// AgentList calls "agent.list".
func (c *Client) AgentList(ctx context.Context) (*AgentListResponse, error) {
	raw, err := c.CallRaw(ctx, MethodAgentList, nil)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodAgentList, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentListResponse)
	if !ok {
		return nil, opError(MethodAgentList, OpDecode, &UnexpectedResultError{Method: MethodAgentList, Want: "agent_list", Got: result.ResultType()})
	}
	return typed, nil
}

// AgentPrompt calls "agent.prompt".
func (c *Client) AgentPrompt(ctx context.Context, params AgentPromptParams) (*AgentPromptedResponse, error) {
	raw, err := c.CallRaw(ctx, MethodAgentPrompt, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodAgentPrompt, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentPromptedResponse)
	if !ok {
		return nil, opError(MethodAgentPrompt, OpDecode, &UnexpectedResultError{Method: MethodAgentPrompt, Want: "agent_prompted", Got: result.ResultType()})
	}
	return typed, nil
}

// AgentRead calls "agent.read".
func (c *Client) AgentRead(ctx context.Context, params AgentReadParams) (*PaneReadResponse, error) {
	raw, err := c.CallRaw(ctx, MethodAgentRead, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodAgentRead, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneReadResponse)
	if !ok {
		return nil, opError(MethodAgentRead, OpDecode, &UnexpectedResultError{Method: MethodAgentRead, Want: "pane_read", Got: result.ResultType()})
	}
	return typed, nil
}

// AgentRename calls "agent.rename".
func (c *Client) AgentRename(ctx context.Context, params AgentRenameParams) (*AgentInfoResponse, error) {
	raw, err := c.CallRaw(ctx, MethodAgentRename, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodAgentRename, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentInfoResponse)
	if !ok {
		return nil, opError(MethodAgentRename, OpDecode, &UnexpectedResultError{Method: MethodAgentRename, Want: "agent_info", Got: result.ResultType()})
	}
	return typed, nil
}

// AgentSendKeys calls "agent.send_keys".
func (c *Client) AgentSendKeys(ctx context.Context, params AgentSendKeysParams) (*OKResponse, error) {
	raw, err := c.CallRaw(ctx, MethodAgentSendKeys, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodAgentSendKeys, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResponse)
	if !ok {
		return nil, opError(MethodAgentSendKeys, OpDecode, &UnexpectedResultError{Method: MethodAgentSendKeys, Want: "ok", Got: result.ResultType()})
	}
	return typed, nil
}

// AgentStart calls "agent.start".
func (c *Client) AgentStart(ctx context.Context, params AgentStartParams) (*AgentStartedResponse, error) {
	raw, err := c.CallRaw(ctx, MethodAgentStart, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodAgentStart, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentStartedResponse)
	if !ok {
		return nil, opError(MethodAgentStart, OpDecode, &UnexpectedResultError{Method: MethodAgentStart, Want: "agent_started", Got: result.ResultType()})
	}
	return typed, nil
}

// AgentViewClear calls "agent.view.clear".
func (c *Client) AgentViewClear(ctx context.Context, params AgentViewClearParams) (*AgentViewResponse, error) {
	raw, err := c.CallRaw(ctx, MethodAgentViewClear, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodAgentViewClear, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentViewResponse)
	if !ok {
		return nil, opError(MethodAgentViewClear, OpDecode, &UnexpectedResultError{Method: MethodAgentViewClear, Want: "agent_view", Got: result.ResultType()})
	}
	return typed, nil
}

// AgentViewSet calls "agent.view.set".
func (c *Client) AgentViewSet(ctx context.Context, params AgentViewSetParams) (*AgentViewResponse, error) {
	raw, err := c.CallRaw(ctx, MethodAgentViewSet, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodAgentViewSet, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentViewResponse)
	if !ok {
		return nil, opError(MethodAgentViewSet, OpDecode, &UnexpectedResultError{Method: MethodAgentViewSet, Want: "agent_view", Got: result.ResultType()})
	}
	return typed, nil
}

// AgentWait calls "agent.wait".
func (c *Client) AgentWait(ctx context.Context, params AgentWaitParams) (*AgentInfoResponse, error) {
	raw, err := c.CallRaw(ctx, MethodAgentWait, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodAgentWait, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentInfoResponse)
	if !ok {
		return nil, opError(MethodAgentWait, OpDecode, &UnexpectedResultError{Method: MethodAgentWait, Want: "agent_info", Got: result.ResultType()})
	}
	return typed, nil
}

// ClientShellSurfaceSet calls "client_shell.surface.set".
func (c *Client) ClientShellSurfaceSet(ctx context.Context, params ClientShellSurfaceSetParams) (*ClientShellSurfaceSetResponse, error) {
	raw, err := c.CallRaw(ctx, MethodClientShellSurfaceSet, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodClientShellSurfaceSet, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*ClientShellSurfaceSetResponse)
	if !ok {
		return nil, opError(MethodClientShellSurfaceSet, OpDecode, &UnexpectedResultError{Method: MethodClientShellSurfaceSet, Want: "client_shell_surface_set", Got: result.ResultType()})
	}
	return typed, nil
}

// ClientWindowTitleClear calls "client.window_title.clear".
func (c *Client) ClientWindowTitleClear(ctx context.Context) (*ClientWindowTitleResponse, error) {
	raw, err := c.CallRaw(ctx, MethodClientWindowTitleClear, nil)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodClientWindowTitleClear, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*ClientWindowTitleResponse)
	if !ok {
		return nil, opError(MethodClientWindowTitleClear, OpDecode, &UnexpectedResultError{Method: MethodClientWindowTitleClear, Want: "client_window_title", Got: result.ResultType()})
	}
	return typed, nil
}

// ClientWindowTitleSet calls "client.window_title.set".
func (c *Client) ClientWindowTitleSet(ctx context.Context, params ClientWindowTitleSetParams) (*ClientWindowTitleResponse, error) {
	raw, err := c.CallRaw(ctx, MethodClientWindowTitleSet, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodClientWindowTitleSet, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*ClientWindowTitleResponse)
	if !ok {
		return nil, opError(MethodClientWindowTitleSet, OpDecode, &UnexpectedResultError{Method: MethodClientWindowTitleSet, Want: "client_window_title", Got: result.ResultType()})
	}
	return typed, nil
}

// CommandInvoke calls "command.invoke". The method answers with more than
// one result type, so the result is returned as a Result.
func (c *Client) CommandInvoke(ctx context.Context, params CommandInvokeParams) (Result, error) {
	raw, err := c.CallRaw(ctx, MethodCommandInvoke, params)
	if err != nil {
		return nil, err
	}
	return decodeResult(MethodCommandInvoke, raw)
}

// EventsSubscribe calls "events.subscribe" and keeps the connection open.
// Read the pushed events with (*Stream).NextEvent.
func (c *Client) EventsSubscribe(ctx context.Context, params EventsSubscribeParams) (*Stream, error) {
	return c.OpenStream(ctx, MethodEventsSubscribe, params)
}

// EventsWait calls "events.wait".
func (c *Client) EventsWait(ctx context.Context, params EventsWaitParams) (*WaitMatchedResponse, error) {
	raw, err := c.CallRaw(ctx, MethodEventsWait, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodEventsWait, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WaitMatchedResponse)
	if !ok {
		return nil, opError(MethodEventsWait, OpDecode, &UnexpectedResultError{Method: MethodEventsWait, Want: "wait_matched", Got: result.ResultType()})
	}
	return typed, nil
}

// IntegrationInstall calls "integration.install".
func (c *Client) IntegrationInstall(ctx context.Context, params IntegrationInstallParams) (*IntegrationInstallResponse, error) {
	raw, err := c.CallRaw(ctx, MethodIntegrationInstall, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodIntegrationInstall, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*IntegrationInstallResponse)
	if !ok {
		return nil, opError(MethodIntegrationInstall, OpDecode, &UnexpectedResultError{Method: MethodIntegrationInstall, Want: "integration_install", Got: result.ResultType()})
	}
	return typed, nil
}

// IntegrationList calls "integration.list".
func (c *Client) IntegrationList(ctx context.Context) (*IntegrationListResponse, error) {
	raw, err := c.CallRaw(ctx, MethodIntegrationList, nil)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodIntegrationList, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*IntegrationListResponse)
	if !ok {
		return nil, opError(MethodIntegrationList, OpDecode, &UnexpectedResultError{Method: MethodIntegrationList, Want: "integration_list", Got: result.ResultType()})
	}
	return typed, nil
}

// IntegrationUninstall calls "integration.uninstall".
func (c *Client) IntegrationUninstall(ctx context.Context, params IntegrationUninstallParams) (*IntegrationUninstallResponse, error) {
	raw, err := c.CallRaw(ctx, MethodIntegrationUninstall, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodIntegrationUninstall, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*IntegrationUninstallResponse)
	if !ok {
		return nil, opError(MethodIntegrationUninstall, OpDecode, &UnexpectedResultError{Method: MethodIntegrationUninstall, Want: "integration_uninstall", Got: result.ResultType()})
	}
	return typed, nil
}

// LayoutApply calls "layout.apply".
func (c *Client) LayoutApply(ctx context.Context, params LayoutApplyParams) (*LayoutApplyResponse, error) {
	raw, err := c.CallRaw(ctx, MethodLayoutApply, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodLayoutApply, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*LayoutApplyResponse)
	if !ok {
		return nil, opError(MethodLayoutApply, OpDecode, &UnexpectedResultError{Method: MethodLayoutApply, Want: "layout_apply", Got: result.ResultType()})
	}
	return typed, nil
}

// LayoutExport calls "layout.export".
func (c *Client) LayoutExport(ctx context.Context, params LayoutExportParams) (*LayoutExportResponse, error) {
	raw, err := c.CallRaw(ctx, MethodLayoutExport, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodLayoutExport, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*LayoutExportResponse)
	if !ok {
		return nil, opError(MethodLayoutExport, OpDecode, &UnexpectedResultError{Method: MethodLayoutExport, Want: "layout_export", Got: result.ResultType()})
	}
	return typed, nil
}

// LayoutSetSplitRatio calls "layout.set_split_ratio".
func (c *Client) LayoutSetSplitRatio(ctx context.Context, params LayoutSetSplitRatioParams) (*LayoutSplitRatioSetResponse, error) {
	raw, err := c.CallRaw(ctx, MethodLayoutSetSplitRatio, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodLayoutSetSplitRatio, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*LayoutSplitRatioSetResponse)
	if !ok {
		return nil, opError(MethodLayoutSetSplitRatio, OpDecode, &UnexpectedResultError{Method: MethodLayoutSetSplitRatio, Want: "layout_split_ratio_set", Got: result.ResultType()})
	}
	return typed, nil
}

// NotificationShow calls "notification.show".
func (c *Client) NotificationShow(ctx context.Context, params NotificationShowParams) (*NotificationShowResponse, error) {
	raw, err := c.CallRaw(ctx, MethodNotificationShow, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodNotificationShow, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*NotificationShowResponse)
	if !ok {
		return nil, opError(MethodNotificationShow, OpDecode, &UnexpectedResultError{Method: MethodNotificationShow, Want: "notification_show", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneClearAgentAuthority calls "pane.clear_agent_authority".
func (c *Client) PaneClearAgentAuthority(ctx context.Context, params PaneClearAgentAuthorityParams) (*OKResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneClearAgentAuthority, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneClearAgentAuthority, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResponse)
	if !ok {
		return nil, opError(MethodPaneClearAgentAuthority, OpDecode, &UnexpectedResultError{Method: MethodPaneClearAgentAuthority, Want: "ok", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneClose calls "pane.close".
func (c *Client) PaneClose(ctx context.Context, params PaneTarget) (*OKResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneClose, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneClose, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResponse)
	if !ok {
		return nil, opError(MethodPaneClose, OpDecode, &UnexpectedResultError{Method: MethodPaneClose, Want: "ok", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneCopyMotion calls "pane.copy_motion".
func (c *Client) PaneCopyMotion(ctx context.Context, params PaneCopyMotionParams) (*PaneCopyMotionResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneCopyMotion, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneCopyMotion, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneCopyMotionResponse)
	if !ok {
		return nil, opError(MethodPaneCopyMotion, OpDecode, &UnexpectedResultError{Method: MethodPaneCopyMotion, Want: "pane_copy_motion", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneCopySearch calls "pane.copy_search".
func (c *Client) PaneCopySearch(ctx context.Context, params PaneCopySearchParams) (*PaneCopySearchResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneCopySearch, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneCopySearch, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneCopySearchResponse)
	if !ok {
		return nil, opError(MethodPaneCopySearch, OpDecode, &UnexpectedResultError{Method: MethodPaneCopySearch, Want: "pane_copy_search", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneCurrent calls "pane.current".
func (c *Client) PaneCurrent(ctx context.Context, params PaneCurrentParams) (*PaneCurrentResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneCurrent, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneCurrent, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneCurrentResponse)
	if !ok {
		return nil, opError(MethodPaneCurrent, OpDecode, &UnexpectedResultError{Method: MethodPaneCurrent, Want: "pane_current", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneEdges calls "pane.edges".
func (c *Client) PaneEdges(ctx context.Context, params PaneEdgesParams) (*PaneEdgesResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneEdges, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneEdges, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneEdgesResponse)
	if !ok {
		return nil, opError(MethodPaneEdges, OpDecode, &UnexpectedResultError{Method: MethodPaneEdges, Want: "pane_edges", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneEditScrollback calls "pane.edit_scrollback".
func (c *Client) PaneEditScrollback(ctx context.Context, params PaneTarget) (*OKResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneEditScrollback, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneEditScrollback, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResponse)
	if !ok {
		return nil, opError(MethodPaneEditScrollback, OpDecode, &UnexpectedResultError{Method: MethodPaneEditScrollback, Want: "ok", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneFocus calls "pane.focus".
func (c *Client) PaneFocus(ctx context.Context, params PaneTarget) (*PaneInfoResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneFocus, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneFocus, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneInfoResponse)
	if !ok {
		return nil, opError(MethodPaneFocus, OpDecode, &UnexpectedResultError{Method: MethodPaneFocus, Want: "pane_info", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneFocusDirection calls "pane.focus_direction".
func (c *Client) PaneFocusDirection(ctx context.Context, params PaneFocusDirectionParams) (*PaneFocusDirectionResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneFocusDirection, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneFocusDirection, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneFocusDirectionResponse)
	if !ok {
		return nil, opError(MethodPaneFocusDirection, OpDecode, &UnexpectedResultError{Method: MethodPaneFocusDirection, Want: "pane_focus_direction", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneGet calls "pane.get".
func (c *Client) PaneGet(ctx context.Context, params PaneTarget) (*PaneInfoResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneGet, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneGet, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneInfoResponse)
	if !ok {
		return nil, opError(MethodPaneGet, OpDecode, &UnexpectedResultError{Method: MethodPaneGet, Want: "pane_info", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneGraphicsClear calls "pane.graphics.clear".
func (c *Client) PaneGraphicsClear(ctx context.Context, params PaneGraphicsClearParams) (*OKResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneGraphicsClear, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneGraphicsClear, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResponse)
	if !ok {
		return nil, opError(MethodPaneGraphicsClear, OpDecode, &UnexpectedResultError{Method: MethodPaneGraphicsClear, Want: "ok", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneGraphicsInfo calls "pane.graphics.info".
func (c *Client) PaneGraphicsInfo(ctx context.Context, params PaneTarget) (*PaneGraphicsInfoResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneGraphicsInfo, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneGraphicsInfo, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneGraphicsInfoResponse)
	if !ok {
		return nil, opError(MethodPaneGraphicsInfo, OpDecode, &UnexpectedResultError{Method: MethodPaneGraphicsInfo, Want: "pane_graphics_info", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneGraphicsSet calls "pane.graphics.set".
func (c *Client) PaneGraphicsSet(ctx context.Context, params PaneGraphicsSetParams) (*OKResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneGraphicsSet, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneGraphicsSet, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResponse)
	if !ok {
		return nil, opError(MethodPaneGraphicsSet, OpDecode, &UnexpectedResultError{Method: MethodPaneGraphicsSet, Want: "ok", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneInputSet calls "pane.input.set".
func (c *Client) PaneInputSet(ctx context.Context, params PaneInputSetParams) (*OKResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneInputSet, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneInputSet, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResponse)
	if !ok {
		return nil, opError(MethodPaneInputSet, OpDecode, &UnexpectedResultError{Method: MethodPaneInputSet, Want: "ok", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneLayout calls "pane.layout".
func (c *Client) PaneLayout(ctx context.Context, params PaneLayoutParams) (*PaneLayoutResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneLayout, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneLayout, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneLayoutResponse)
	if !ok {
		return nil, opError(MethodPaneLayout, OpDecode, &UnexpectedResultError{Method: MethodPaneLayout, Want: "pane_layout", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneLinkActivate calls "pane.link.activate".
func (c *Client) PaneLinkActivate(ctx context.Context, params PaneLinkActivateParams) (*PaneLinkActivatedResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneLinkActivate, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneLinkActivate, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneLinkActivatedResponse)
	if !ok {
		return nil, opError(MethodPaneLinkActivate, OpDecode, &UnexpectedResultError{Method: MethodPaneLinkActivate, Want: "pane_link_activated", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneLinkResolve calls "pane.link.resolve".
func (c *Client) PaneLinkResolve(ctx context.Context, params PaneLinkActivateParams) (*PaneLinkResolvedResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneLinkResolve, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneLinkResolve, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneLinkResolvedResponse)
	if !ok {
		return nil, opError(MethodPaneLinkResolve, OpDecode, &UnexpectedResultError{Method: MethodPaneLinkResolve, Want: "pane_link_resolved", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneList calls "pane.list".
func (c *Client) PaneList(ctx context.Context, params PaneListParams) (*PaneListResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneList, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneList, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneListResponse)
	if !ok {
		return nil, opError(MethodPaneList, OpDecode, &UnexpectedResultError{Method: MethodPaneList, Want: "pane_list", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneMove calls "pane.move".
func (c *Client) PaneMove(ctx context.Context, params PaneMoveParams) (*PaneMoveResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneMove, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneMove, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneMoveResponse)
	if !ok {
		return nil, opError(MethodPaneMove, OpDecode, &UnexpectedResultError{Method: MethodPaneMove, Want: "pane_move", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneNeighbor calls "pane.neighbor".
func (c *Client) PaneNeighbor(ctx context.Context, params PaneNeighborParams) (*PaneNeighborResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneNeighbor, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneNeighbor, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneNeighborResponse)
	if !ok {
		return nil, opError(MethodPaneNeighbor, OpDecode, &UnexpectedResultError{Method: MethodPaneNeighbor, Want: "pane_neighbor", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneProcessInfo calls "pane.process_info".
func (c *Client) PaneProcessInfo(ctx context.Context, params PaneProcessInfoParams) (*PaneProcessInfoResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneProcessInfo, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneProcessInfo, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneProcessInfoResponse)
	if !ok {
		return nil, opError(MethodPaneProcessInfo, OpDecode, &UnexpectedResultError{Method: MethodPaneProcessInfo, Want: "pane_process_info", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneRead calls "pane.read".
func (c *Client) PaneRead(ctx context.Context, params PaneReadParams) (*PaneReadResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneRead, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneRead, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneReadResponse)
	if !ok {
		return nil, opError(MethodPaneRead, OpDecode, &UnexpectedResultError{Method: MethodPaneRead, Want: "pane_read", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneReleaseAgent calls "pane.release_agent".
func (c *Client) PaneReleaseAgent(ctx context.Context, params PaneReleaseAgentParams) (*OKResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneReleaseAgent, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneReleaseAgent, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResponse)
	if !ok {
		return nil, opError(MethodPaneReleaseAgent, OpDecode, &UnexpectedResultError{Method: MethodPaneReleaseAgent, Want: "ok", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneRename calls "pane.rename".
func (c *Client) PaneRename(ctx context.Context, params PaneRenameParams) (*PaneInfoResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneRename, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneRename, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneInfoResponse)
	if !ok {
		return nil, opError(MethodPaneRename, OpDecode, &UnexpectedResultError{Method: MethodPaneRename, Want: "pane_info", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneReportAgent calls "pane.report_agent".
func (c *Client) PaneReportAgent(ctx context.Context, params PaneReportAgentParams) (*OKResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneReportAgent, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneReportAgent, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResponse)
	if !ok {
		return nil, opError(MethodPaneReportAgent, OpDecode, &UnexpectedResultError{Method: MethodPaneReportAgent, Want: "ok", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneReportAgentSession calls "pane.report_agent_session".
func (c *Client) PaneReportAgentSession(ctx context.Context, params PaneReportAgentSessionParams) (*OKResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneReportAgentSession, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneReportAgentSession, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResponse)
	if !ok {
		return nil, opError(MethodPaneReportAgentSession, OpDecode, &UnexpectedResultError{Method: MethodPaneReportAgentSession, Want: "ok", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneReportMetadata calls "pane.report_metadata".
func (c *Client) PaneReportMetadata(ctx context.Context, params PaneReportMetadataParams) (*OKResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneReportMetadata, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneReportMetadata, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResponse)
	if !ok {
		return nil, opError(MethodPaneReportMetadata, OpDecode, &UnexpectedResultError{Method: MethodPaneReportMetadata, Want: "ok", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneResize calls "pane.resize".
func (c *Client) PaneResize(ctx context.Context, params PaneResizeParams) (*PaneResizeResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneResize, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneResize, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneResizeResponse)
	if !ok {
		return nil, opError(MethodPaneResize, OpDecode, &UnexpectedResultError{Method: MethodPaneResize, Want: "pane_resize", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneScroll calls "pane.scroll".
func (c *Client) PaneScroll(ctx context.Context, params PaneScrollParams) (*PaneInfoResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneScroll, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneScroll, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneInfoResponse)
	if !ok {
		return nil, opError(MethodPaneScroll, OpDecode, &UnexpectedResultError{Method: MethodPaneScroll, Want: "pane_info", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneSelectionRead calls "pane.selection.read".
func (c *Client) PaneSelectionRead(ctx context.Context, params PaneSelectionReadParams) (*PaneSelectionResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneSelectionRead, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneSelectionRead, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneSelectionResponse)
	if !ok {
		return nil, opError(MethodPaneSelectionRead, OpDecode, &UnexpectedResultError{Method: MethodPaneSelectionRead, Want: "pane_selection", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneSendInput calls "pane.send_input".
func (c *Client) PaneSendInput(ctx context.Context, params PaneSendInputParams) (*OKResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneSendInput, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneSendInput, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResponse)
	if !ok {
		return nil, opError(MethodPaneSendInput, OpDecode, &UnexpectedResultError{Method: MethodPaneSendInput, Want: "ok", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneSendKeys calls "pane.send_keys".
func (c *Client) PaneSendKeys(ctx context.Context, params PaneSendKeysParams) (*OKResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneSendKeys, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneSendKeys, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResponse)
	if !ok {
		return nil, opError(MethodPaneSendKeys, OpDecode, &UnexpectedResultError{Method: MethodPaneSendKeys, Want: "ok", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneSendText calls "pane.send_text".
func (c *Client) PaneSendText(ctx context.Context, params PaneSendTextParams) (*OKResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneSendText, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneSendText, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResponse)
	if !ok {
		return nil, opError(MethodPaneSendText, OpDecode, &UnexpectedResultError{Method: MethodPaneSendText, Want: "ok", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneSplit calls "pane.split".
func (c *Client) PaneSplit(ctx context.Context, params PaneSplitParams) (*PaneInfoResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneSplit, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneSplit, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneInfoResponse)
	if !ok {
		return nil, opError(MethodPaneSplit, OpDecode, &UnexpectedResultError{Method: MethodPaneSplit, Want: "pane_info", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneSwap calls "pane.swap".
func (c *Client) PaneSwap(ctx context.Context, params PaneSwapParams) (*PaneSwapResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneSwap, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneSwap, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneSwapResponse)
	if !ok {
		return nil, opError(MethodPaneSwap, OpDecode, &UnexpectedResultError{Method: MethodPaneSwap, Want: "pane_swap", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneWaitForOutput calls "pane.wait_for_output".
func (c *Client) PaneWaitForOutput(ctx context.Context, params PaneWaitForOutputParams) (*OutputMatchedResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneWaitForOutput, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneWaitForOutput, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OutputMatchedResponse)
	if !ok {
		return nil, opError(MethodPaneWaitForOutput, OpDecode, &UnexpectedResultError{Method: MethodPaneWaitForOutput, Want: "output_matched", Got: result.ResultType()})
	}
	return typed, nil
}

// PaneZoom calls "pane.zoom".
func (c *Client) PaneZoom(ctx context.Context, params PaneZoomParams) (*PaneZoomResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPaneZoom, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPaneZoom, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneZoomResponse)
	if !ok {
		return nil, opError(MethodPaneZoom, OpDecode, &UnexpectedResultError{Method: MethodPaneZoom, Want: "pane_zoom", Got: result.ResultType()})
	}
	return typed, nil
}

// Ping calls "ping".
func (c *Client) Ping(ctx context.Context) (*PongResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPing, nil)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPing, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PongResponse)
	if !ok {
		return nil, opError(MethodPing, OpDecode, &UnexpectedResultError{Method: MethodPing, Want: "pong", Got: result.ResultType()})
	}
	return typed, nil
}

// PluginActionInvoke calls "plugin.action.invoke".
func (c *Client) PluginActionInvoke(ctx context.Context, params PluginActionInvokeParams) (*PluginActionInvokedResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPluginActionInvoke, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPluginActionInvoke, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PluginActionInvokedResponse)
	if !ok {
		return nil, opError(MethodPluginActionInvoke, OpDecode, &UnexpectedResultError{Method: MethodPluginActionInvoke, Want: "plugin_action_invoked", Got: result.ResultType()})
	}
	return typed, nil
}

// PluginActionList calls "plugin.action.list".
func (c *Client) PluginActionList(ctx context.Context, params PluginActionListParams) (*PluginActionListResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPluginActionList, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPluginActionList, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PluginActionListResponse)
	if !ok {
		return nil, opError(MethodPluginActionList, OpDecode, &UnexpectedResultError{Method: MethodPluginActionList, Want: "plugin_action_list", Got: result.ResultType()})
	}
	return typed, nil
}

// PluginDisable calls "plugin.disable".
func (c *Client) PluginDisable(ctx context.Context, params PluginSetEnabledParams) (*PluginDisabledResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPluginDisable, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPluginDisable, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PluginDisabledResponse)
	if !ok {
		return nil, opError(MethodPluginDisable, OpDecode, &UnexpectedResultError{Method: MethodPluginDisable, Want: "plugin_disabled", Got: result.ResultType()})
	}
	return typed, nil
}

// PluginEnable calls "plugin.enable".
func (c *Client) PluginEnable(ctx context.Context, params PluginSetEnabledParams) (*PluginEnabledResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPluginEnable, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPluginEnable, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PluginEnabledResponse)
	if !ok {
		return nil, opError(MethodPluginEnable, OpDecode, &UnexpectedResultError{Method: MethodPluginEnable, Want: "plugin_enabled", Got: result.ResultType()})
	}
	return typed, nil
}

// PluginLink calls "plugin.link".
func (c *Client) PluginLink(ctx context.Context, params PluginLinkParams) (*PluginLinkedResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPluginLink, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPluginLink, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PluginLinkedResponse)
	if !ok {
		return nil, opError(MethodPluginLink, OpDecode, &UnexpectedResultError{Method: MethodPluginLink, Want: "plugin_linked", Got: result.ResultType()})
	}
	return typed, nil
}

// PluginList calls "plugin.list".
func (c *Client) PluginList(ctx context.Context, params PluginListParams) (*PluginListResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPluginList, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPluginList, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PluginListResponse)
	if !ok {
		return nil, opError(MethodPluginList, OpDecode, &UnexpectedResultError{Method: MethodPluginList, Want: "plugin_list", Got: result.ResultType()})
	}
	return typed, nil
}

// PluginLogList calls "plugin.log.list".
func (c *Client) PluginLogList(ctx context.Context, params PluginLogListParams) (*PluginLogListResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPluginLogList, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPluginLogList, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PluginLogListResponse)
	if !ok {
		return nil, opError(MethodPluginLogList, OpDecode, &UnexpectedResultError{Method: MethodPluginLogList, Want: "plugin_log_list", Got: result.ResultType()})
	}
	return typed, nil
}

// PluginPaneClose calls "plugin.pane.close".
func (c *Client) PluginPaneClose(ctx context.Context, params PluginPaneCloseParams) (*PluginPaneClosedResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPluginPaneClose, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPluginPaneClose, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PluginPaneClosedResponse)
	if !ok {
		return nil, opError(MethodPluginPaneClose, OpDecode, &UnexpectedResultError{Method: MethodPluginPaneClose, Want: "plugin_pane_closed", Got: result.ResultType()})
	}
	return typed, nil
}

// PluginPaneFocus calls "plugin.pane.focus".
func (c *Client) PluginPaneFocus(ctx context.Context, params PluginPaneFocusParams) (*PluginPaneFocusedResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPluginPaneFocus, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPluginPaneFocus, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PluginPaneFocusedResponse)
	if !ok {
		return nil, opError(MethodPluginPaneFocus, OpDecode, &UnexpectedResultError{Method: MethodPluginPaneFocus, Want: "plugin_pane_focused", Got: result.ResultType()})
	}
	return typed, nil
}

// PluginPaneOpen calls "plugin.pane.open". The result is one of
// *PluginPaneOpenedResponse or *OKResponse.
func (c *Client) PluginPaneOpen(ctx context.Context, params PluginPaneOpenParams) (Result, error) {
	raw, err := c.CallRaw(ctx, MethodPluginPaneOpen, params)
	if err != nil {
		return nil, err
	}
	return decodeResult(MethodPluginPaneOpen, raw)
}

// PluginUnlink calls "plugin.unlink".
func (c *Client) PluginUnlink(ctx context.Context, params PluginUnlinkParams) (*PluginUnlinkedResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPluginUnlink, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPluginUnlink, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PluginUnlinkedResponse)
	if !ok {
		return nil, opError(MethodPluginUnlink, OpDecode, &UnexpectedResultError{Method: MethodPluginUnlink, Want: "plugin_unlinked", Got: result.ResultType()})
	}
	return typed, nil
}

// PopupClose calls "popup.close".
func (c *Client) PopupClose(ctx context.Context) (*OKResponse, error) {
	raw, err := c.CallRaw(ctx, MethodPopupClose, nil)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodPopupClose, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResponse)
	if !ok {
		return nil, opError(MethodPopupClose, OpDecode, &UnexpectedResultError{Method: MethodPopupClose, Want: "ok", Got: result.ResultType()})
	}
	return typed, nil
}

// ProductAnnouncementDismiss calls "product_announcement.dismiss".
func (c *Client) ProductAnnouncementDismiss(ctx context.Context, params ProductAnnouncementDismissParams) (*OKResponse, error) {
	raw, err := c.CallRaw(ctx, MethodProductAnnouncementDismiss, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodProductAnnouncementDismiss, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResponse)
	if !ok {
		return nil, opError(MethodProductAnnouncementDismiss, OpDecode, &UnexpectedResultError{Method: MethodProductAnnouncementDismiss, Want: "ok", Got: result.ResultType()})
	}
	return typed, nil
}

// ReleaseNotesDismiss calls "release_notes.dismiss".
func (c *Client) ReleaseNotesDismiss(ctx context.Context, params ReleaseNotesDismissParams) (*OKResponse, error) {
	raw, err := c.CallRaw(ctx, MethodReleaseNotesDismiss, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodReleaseNotesDismiss, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResponse)
	if !ok {
		return nil, opError(MethodReleaseNotesDismiss, OpDecode, &UnexpectedResultError{Method: MethodReleaseNotesDismiss, Want: "ok", Got: result.ResultType()})
	}
	return typed, nil
}

// ServerAgentManifests calls "server.agent_manifests".
func (c *Client) ServerAgentManifests(ctx context.Context) (*AgentManifestStatusResponse, error) {
	raw, err := c.CallRaw(ctx, MethodServerAgentManifests, nil)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodServerAgentManifests, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentManifestStatusResponse)
	if !ok {
		return nil, opError(MethodServerAgentManifests, OpDecode, &UnexpectedResultError{Method: MethodServerAgentManifests, Want: "agent_manifest_status", Got: result.ResultType()})
	}
	return typed, nil
}

// ServerLiveHandoff calls "server.live_handoff". The method answers with
// more than one result type, so the result is returned as a Result.
func (c *Client) ServerLiveHandoff(ctx context.Context, params ServerLiveHandoffParams) (Result, error) {
	raw, err := c.CallRaw(ctx, MethodServerLiveHandoff, params)
	if err != nil {
		return nil, err
	}
	return decodeResult(MethodServerLiveHandoff, raw)
}

// ServerReloadAgentManifests calls "server.reload_agent_manifests".
func (c *Client) ServerReloadAgentManifests(ctx context.Context) (*AgentManifestReloadResponse, error) {
	raw, err := c.CallRaw(ctx, MethodServerReloadAgentManifests, nil)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodServerReloadAgentManifests, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentManifestReloadResponse)
	if !ok {
		return nil, opError(MethodServerReloadAgentManifests, OpDecode, &UnexpectedResultError{Method: MethodServerReloadAgentManifests, Want: "agent_manifest_reload", Got: result.ResultType()})
	}
	return typed, nil
}

// ServerReloadConfig calls "server.reload_config".
func (c *Client) ServerReloadConfig(ctx context.Context) (*ConfigReloadResponse, error) {
	raw, err := c.CallRaw(ctx, MethodServerReloadConfig, nil)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodServerReloadConfig, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*ConfigReloadResponse)
	if !ok {
		return nil, opError(MethodServerReloadConfig, OpDecode, &UnexpectedResultError{Method: MethodServerReloadConfig, Want: "config_reload", Got: result.ResultType()})
	}
	return typed, nil
}

// ServerStop calls "server.stop".
func (c *Client) ServerStop(ctx context.Context) (*OKResponse, error) {
	raw, err := c.CallRaw(ctx, MethodServerStop, nil)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodServerStop, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResponse)
	if !ok {
		return nil, opError(MethodServerStop, OpDecode, &UnexpectedResultError{Method: MethodServerStop, Want: "ok", Got: result.ResultType()})
	}
	return typed, nil
}

// SessionSnapshot calls "session.snapshot".
func (c *Client) SessionSnapshot(ctx context.Context) (*SessionSnapshotResponse, error) {
	raw, err := c.CallRaw(ctx, MethodSessionSnapshot, nil)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodSessionSnapshot, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*SessionSnapshotResponse)
	if !ok {
		return nil, opError(MethodSessionSnapshot, OpDecode, &UnexpectedResultError{Method: MethodSessionSnapshot, Want: "session_snapshot", Got: result.ResultType()})
	}
	return typed, nil
}

// TabClose calls "tab.close".
func (c *Client) TabClose(ctx context.Context, params TabTarget) (*OKResponse, error) {
	raw, err := c.CallRaw(ctx, MethodTabClose, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodTabClose, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResponse)
	if !ok {
		return nil, opError(MethodTabClose, OpDecode, &UnexpectedResultError{Method: MethodTabClose, Want: "ok", Got: result.ResultType()})
	}
	return typed, nil
}

// TabCreate calls "tab.create".
func (c *Client) TabCreate(ctx context.Context, params TabCreateParams) (*TabCreatedResponse, error) {
	raw, err := c.CallRaw(ctx, MethodTabCreate, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodTabCreate, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*TabCreatedResponse)
	if !ok {
		return nil, opError(MethodTabCreate, OpDecode, &UnexpectedResultError{Method: MethodTabCreate, Want: "tab_created", Got: result.ResultType()})
	}
	return typed, nil
}

// TabFocus calls "tab.focus".
func (c *Client) TabFocus(ctx context.Context, params TabTarget) (*TabInfoResponse, error) {
	raw, err := c.CallRaw(ctx, MethodTabFocus, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodTabFocus, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*TabInfoResponse)
	if !ok {
		return nil, opError(MethodTabFocus, OpDecode, &UnexpectedResultError{Method: MethodTabFocus, Want: "tab_info", Got: result.ResultType()})
	}
	return typed, nil
}

// TabGet calls "tab.get".
func (c *Client) TabGet(ctx context.Context, params TabTarget) (*TabInfoResponse, error) {
	raw, err := c.CallRaw(ctx, MethodTabGet, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodTabGet, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*TabInfoResponse)
	if !ok {
		return nil, opError(MethodTabGet, OpDecode, &UnexpectedResultError{Method: MethodTabGet, Want: "tab_info", Got: result.ResultType()})
	}
	return typed, nil
}

// TabList calls "tab.list".
func (c *Client) TabList(ctx context.Context, params TabListParams) (*TabListResponse, error) {
	raw, err := c.CallRaw(ctx, MethodTabList, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodTabList, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*TabListResponse)
	if !ok {
		return nil, opError(MethodTabList, OpDecode, &UnexpectedResultError{Method: MethodTabList, Want: "tab_list", Got: result.ResultType()})
	}
	return typed, nil
}

// TabMove calls "tab.move".
func (c *Client) TabMove(ctx context.Context, params TabMoveParams) (*TabListResponse, error) {
	raw, err := c.CallRaw(ctx, MethodTabMove, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodTabMove, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*TabListResponse)
	if !ok {
		return nil, opError(MethodTabMove, OpDecode, &UnexpectedResultError{Method: MethodTabMove, Want: "tab_list", Got: result.ResultType()})
	}
	return typed, nil
}

// TabRename calls "tab.rename".
func (c *Client) TabRename(ctx context.Context, params TabRenameParams) (*TabInfoResponse, error) {
	raw, err := c.CallRaw(ctx, MethodTabRename, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodTabRename, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*TabInfoResponse)
	if !ok {
		return nil, opError(MethodTabRename, OpDecode, &UnexpectedResultError{Method: MethodTabRename, Want: "tab_info", Got: result.ResultType()})
	}
	return typed, nil
}

// WorkspaceClose calls "workspace.close".
func (c *Client) WorkspaceClose(ctx context.Context, params WorkspaceCloseParams) (*OKResponse, error) {
	raw, err := c.CallRaw(ctx, MethodWorkspaceClose, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodWorkspaceClose, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResponse)
	if !ok {
		return nil, opError(MethodWorkspaceClose, OpDecode, &UnexpectedResultError{Method: MethodWorkspaceClose, Want: "ok", Got: result.ResultType()})
	}
	return typed, nil
}

// WorkspaceCreate calls "workspace.create".
func (c *Client) WorkspaceCreate(ctx context.Context, params WorkspaceCreateParams) (*WorkspaceCreatedResponse, error) {
	raw, err := c.CallRaw(ctx, MethodWorkspaceCreate, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodWorkspaceCreate, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WorkspaceCreatedResponse)
	if !ok {
		return nil, opError(MethodWorkspaceCreate, OpDecode, &UnexpectedResultError{Method: MethodWorkspaceCreate, Want: "workspace_created", Got: result.ResultType()})
	}
	return typed, nil
}

// WorkspaceFocus calls "workspace.focus".
func (c *Client) WorkspaceFocus(ctx context.Context, params WorkspaceTarget) (*WorkspaceInfoResponse, error) {
	raw, err := c.CallRaw(ctx, MethodWorkspaceFocus, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodWorkspaceFocus, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WorkspaceInfoResponse)
	if !ok {
		return nil, opError(MethodWorkspaceFocus, OpDecode, &UnexpectedResultError{Method: MethodWorkspaceFocus, Want: "workspace_info", Got: result.ResultType()})
	}
	return typed, nil
}

// WorkspaceGet calls "workspace.get".
func (c *Client) WorkspaceGet(ctx context.Context, params WorkspaceTarget) (*WorkspaceInfoResponse, error) {
	raw, err := c.CallRaw(ctx, MethodWorkspaceGet, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodWorkspaceGet, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WorkspaceInfoResponse)
	if !ok {
		return nil, opError(MethodWorkspaceGet, OpDecode, &UnexpectedResultError{Method: MethodWorkspaceGet, Want: "workspace_info", Got: result.ResultType()})
	}
	return typed, nil
}

// WorkspaceList calls "workspace.list".
func (c *Client) WorkspaceList(ctx context.Context) (*WorkspaceListResponse, error) {
	raw, err := c.CallRaw(ctx, MethodWorkspaceList, nil)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodWorkspaceList, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WorkspaceListResponse)
	if !ok {
		return nil, opError(MethodWorkspaceList, OpDecode, &UnexpectedResultError{Method: MethodWorkspaceList, Want: "workspace_list", Got: result.ResultType()})
	}
	return typed, nil
}

// WorkspaceMove calls "workspace.move".
func (c *Client) WorkspaceMove(ctx context.Context, params WorkspaceMoveParams) (*WorkspaceListResponse, error) {
	raw, err := c.CallRaw(ctx, MethodWorkspaceMove, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodWorkspaceMove, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WorkspaceListResponse)
	if !ok {
		return nil, opError(MethodWorkspaceMove, OpDecode, &UnexpectedResultError{Method: MethodWorkspaceMove, Want: "workspace_list", Got: result.ResultType()})
	}
	return typed, nil
}

// WorkspaceMoveBlock calls "workspace.move_block".
func (c *Client) WorkspaceMoveBlock(ctx context.Context, params WorkspaceMoveBlockParams) (*WorkspaceListResponse, error) {
	raw, err := c.CallRaw(ctx, MethodWorkspaceMoveBlock, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodWorkspaceMoveBlock, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WorkspaceListResponse)
	if !ok {
		return nil, opError(MethodWorkspaceMoveBlock, OpDecode, &UnexpectedResultError{Method: MethodWorkspaceMoveBlock, Want: "workspace_list", Got: result.ResultType()})
	}
	return typed, nil
}

// WorkspaceRename calls "workspace.rename".
func (c *Client) WorkspaceRename(ctx context.Context, params WorkspaceRenameParams) (*WorkspaceInfoResponse, error) {
	raw, err := c.CallRaw(ctx, MethodWorkspaceRename, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodWorkspaceRename, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WorkspaceInfoResponse)
	if !ok {
		return nil, opError(MethodWorkspaceRename, OpDecode, &UnexpectedResultError{Method: MethodWorkspaceRename, Want: "workspace_info", Got: result.ResultType()})
	}
	return typed, nil
}

// WorkspaceReportMetadata calls "workspace.report_metadata".
func (c *Client) WorkspaceReportMetadata(ctx context.Context, params WorkspaceReportMetadataParams) (*OKResponse, error) {
	raw, err := c.CallRaw(ctx, MethodWorkspaceReportMetadata, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodWorkspaceReportMetadata, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResponse)
	if !ok {
		return nil, opError(MethodWorkspaceReportMetadata, OpDecode, &UnexpectedResultError{Method: MethodWorkspaceReportMetadata, Want: "ok", Got: result.ResultType()})
	}
	return typed, nil
}

// WorktreeCreate calls "worktree.create".
func (c *Client) WorktreeCreate(ctx context.Context, params WorktreeCreateParams) (*WorktreeCreatedResponse, error) {
	raw, err := c.CallRaw(ctx, MethodWorktreeCreate, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodWorktreeCreate, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WorktreeCreatedResponse)
	if !ok {
		return nil, opError(MethodWorktreeCreate, OpDecode, &UnexpectedResultError{Method: MethodWorktreeCreate, Want: "worktree_created", Got: result.ResultType()})
	}
	return typed, nil
}

// WorktreeList calls "worktree.list".
func (c *Client) WorktreeList(ctx context.Context, params WorktreeListParams) (*WorktreeListResponse, error) {
	raw, err := c.CallRaw(ctx, MethodWorktreeList, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodWorktreeList, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WorktreeListResponse)
	if !ok {
		return nil, opError(MethodWorktreeList, OpDecode, &UnexpectedResultError{Method: MethodWorktreeList, Want: "worktree_list", Got: result.ResultType()})
	}
	return typed, nil
}

// WorktreeOpen calls "worktree.open".
func (c *Client) WorktreeOpen(ctx context.Context, params WorktreeOpenParams) (*WorktreeOpenedResponse, error) {
	raw, err := c.CallRaw(ctx, MethodWorktreeOpen, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodWorktreeOpen, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WorktreeOpenedResponse)
	if !ok {
		return nil, opError(MethodWorktreeOpen, OpDecode, &UnexpectedResultError{Method: MethodWorktreeOpen, Want: "worktree_opened", Got: result.ResultType()})
	}
	return typed, nil
}

// WorktreeRemove calls "worktree.remove".
func (c *Client) WorktreeRemove(ctx context.Context, params WorktreeRemoveParams) (*WorktreeRemovedResponse, error) {
	raw, err := c.CallRaw(ctx, MethodWorktreeRemove, params)
	if err != nil {
		return nil, err
	}
	result, err := decodeResult(MethodWorktreeRemove, raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WorktreeRemovedResponse)
	if !ok {
		return nil, opError(MethodWorktreeRemove, OpDecode, &UnexpectedResultError{Method: MethodWorktreeRemove, Want: "worktree_removed", Got: result.ResultType()})
	}
	return typed, nil
}
